# Generated by Django 2.1.7 on 2019-03-05 05:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190305_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='even_field',
            field=models.IntegerField(default=0, validators=[blog.models.Post.validation_even]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
