# Generated by Django 2.1.7 on 2019-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
