# Generated by Django 2.1.7 on 2019-03-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_post_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name2',
        ),
    ]
